name: Build and Store Docker Image

on:
  # 使用 workflow_dispatch 事件来允许手动触发
  workflow_dispatch:

jobs:
  build_and_store:
    name: Build and store Docker image as artifact
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          outputs: type=docker,dest=image.tar
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: image.tar
